//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZF.EF.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PressDataEntities : DbContext
    {
        public PressDataEntities()
            : base("name=PressDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Article> t_Article { get; set; }
        public virtual DbSet<t_Base_Menu> t_Base_Menu { get; set; }
        public virtual DbSet<t_Base_Module> t_Base_Module { get; set; }
        public virtual DbSet<t_Base_RegisterUser> t_Base_RegisterUser { get; set; }
        public virtual DbSet<t_Base_User> t_Base_User { get; set; }
        public virtual DbSet<t_Base_UserLoginLog> t_Base_UserLoginLog { get; set; }
        public virtual DbSet<t_Base_OperatorLog> t_Base_OperatorLog { get; set; }
    }
}
