//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZF.EF.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Article
    {
        public string Id { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleContent { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string ArticleImage { get; set; }
    }
}
