//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZF.EF.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Base_OperatorLog
    {
        public string Id { get; set; }
        public int ModuleId { get; set; }
        public string KeyId { get; set; }
        public string OperatorName { get; set; }
        public System.DateTime OperatorDate { get; set; }
        public Nullable<int> OperatorType { get; set; }
        public string OperatorId { get; set; }
        public string Remark { get; set; }
        public string OperatorIp { get; set; }
    }
}
