//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZF.EF.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Base_RegisterUser
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string LoginPwd { get; set; }
        public string TelphoneNum { get; set; }
        public System.DateTime AddTime { get; set; }
        public string RegisterIp { get; set; }
        public string RegiesterType { get; set; }
        public int State { get; set; }
        public string NickNamw { get; set; }
        public string WechatId { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string AreaCode { get; set; }
        public string HeadImage { get; set; }
        public string Code { get; set; }
    }
}
